// Generated 26 Jul 2021 12:51 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Reports
{
    [Serializable]
    public class ProductCategory
     : MEReadOnlyBase<ProductCategory>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<String> CategoryProperty = RegisterProperty<String>(c => c.Category, "ID");
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public String Category
        {
            get { return GetProperty(CategoryProperty); }
        }

        public static PropertyInfo<int> TotalProperty = RegisterProperty<int>(c => c.Total, "Total");
        /// <summary>
        /// Gets the Total value
        /// </summary>
        [Display(Name = "Total", Description = "")]
        public int Total
        {
            get { return GetProperty(TotalProperty); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(CategoryProperty);
        }

        public override string ToString()
        {
            return this.Category;
        }

        #endregion

        #endregion

        #region " Data Access & Factory Methods "

        internal static ProductCategory GetProductCategory(SafeDataReader dr)
        {
            var r = new ProductCategory();
            r.Fetch(dr);
            return r;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            int i = 0;
            LoadProperty(CategoryProperty, sdr.GetString(i++));
            LoadProperty(TotalProperty, sdr.GetInt32(i++));
        }

        #endregion

    }

}