// Generated 23 Jul 2021 10:36 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.TransactionItems
{
    [Serializable]
    public class TransactionItemList
     : MEBusinessListBase<TransactionItemList, TransactionItem>
    {
        #region " Business Methods "

        public TransactionItem GetItem(int TransactionItemID)
        {
            foreach (TransactionItem child in this)
            {
                if (child.TransactionItemID == TransactionItemID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Transaction Items";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static TransactionItemList NewTransactionItemList()
        {
            return new TransactionItemList();
        }

        public TransactionItemList()
        {
            // must have parameter-less constructor
        }

        public static TransactionItemList GetTransactionItemList()
        {
            return DataPortal.Fetch<TransactionItemList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(TransactionItem.GetTransactionItem(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getTransactionItemList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}